[project]
name = "classes-table"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas>=2.3.3",
]


[project.scripts]
out_table = 'classtable.out_table:run'

[tool.uv]
package = true


